Update E2E tests to V4
LDAR-Sim/LDAR_Sim pull request #160
Opened 2024-03-18 15:55 UTC by SEAJang

# Pull Request Key Information

## Reason for change

End to end tests were outdated with the change from V3 to V4 

## What was changed

Updated the end-to-end test suit creator, and the running script and remade 4 basic E2E tests

## Intended Purpose

Update the end-to-end tests from v3 to v4. 

## Testing Completed

Manually tested to see if the scripts ran, and verified the E2E results.

2024-06-20 16:48 UTC, ThomasGalesloot approved these changes
Great work so far - I think this has a little more updating needed to be great

2024-06-20 16:49 UTC, ThomasGalesloot requested changes
Meant to Request changes not approve sorry

2024-06-24 22:10 UTC, SEAJang commented on LDAR_Sim/testing/end_to_end_testing/e2e_suite_runner.py
> +    from initialization.initialize_infrastructure import initialize_infrastructure
The best thing that could be done was to alphabetize them.

2024-06-24 22:39 UTC, SEAJang commented on LDAR_Sim/testing/end_to_end_testing/testing_utils/result_verification.py
> +    with open(out_dir / "parameters.yaml", "r") as params_file:
This does exist, however, we've had the issue where this file is usually one of the key files that is changed during an update. And the point of this E2E is to get the same results even if more parameters are added. 
This code is commented out in the main testing script, but if it's better removed, please let me know.

2024-06-24 22:44 UTC, SEAJang commented
New E2E Test results files:
[V4-simple_all_repairable_9ed4958239661f54f2456b4d0a532e49706d9d6b.log](https://github.com/user-attachments/files/15961995/V4-simple_all_repairable_9ed4958239661f54f2456b4d0a532e49706d9d6b.log)
[V4-simple_all_non_repairable_9ed4958239661f54f2456b4d0a532e49706d9d6b.log](https://github.com/user-attachments/files/15961996/V4-simple_all_non_repairable_9ed4958239661f54f2456b4d0a532e49706d9d6b.log)

All unit existing unit tests pass:
[results.txt](https://github.com/user-attachments/files/15962001/results.txt)

2024-06-26 06:14 UTC, SEAJang commented
All existing unit tests pass. 
[results.txt](https://github.com/user-attachments/files/15983026/results.txt)

All E2E tests pass - ran on a different machine. 
[V4-simple_all_non_repairable_9c4b0ae71517cb6beb0f6e2d73f09e15faa176cf.log](https://github.com/user-attachments/files/15983235/V4-simple_all_non_repairable_9c4b0ae71517cb6beb0f6e2d73f09e15faa176cf.log)
[V4-simple_all_repairable_9c4b0ae71517cb6beb0f6e2d73f09e15faa176cf.log](https://github.com/user-attachments/files/15983236/V4-simple_all_repairable_9c4b0ae71517cb6beb0f6e2d73f09e15faa176cf.log)
[V4-simple_mixed_emissions_9c4b0ae71517cb6beb0f6e2d73f09e15faa176cf.log](https://github.com/user-attachments/files/15983237/V4-simple_mixed_emissions_9c4b0ae71517cb6beb0f6e2d73f09e15faa176cf.log)

2024-06-26 23:03 UTC, ThomasGalesloot approved these changes
Great work - Just address the few small comments and then good to merge. AS a sidenote - we need to think if we really want to compare every output file or just the summary ones.

2024-06-27 05:34 UTC, SEAJang commented on LDAR_Sim/testing/end_to_end_testing/test_suite/V4-simple_all_non_repairable/params/M_OGI.yaml
> +  type: OGI_camera_zim
The OGI sensor if not provided,comes with a default now.

2024-07-12 17:24 UTC, SEAJang commented on LDAR_Sim/testing/end_to_end_testing/e2e_test_case_creator.py
> +    shutil.move(params_dir, test_case_dir)
You do keep the original test case parameters.

2024-07-12 19:47 UTC, SEAJang commented
[results.txt](https://github.com/user-attachments/files/16198693/results.txt)

2024-07-12 19:59 UTC, SEAJang commented
[results.txt](https://github.com/user-attachments/files/16198775/results.txt)

2024-07-12 20:54 UTC, merged