V4 virtual world defining files
LDAR-Sim/LDAR_Sim pull request #200
Opened 2024-06-03 17:40 UTC by SEAJang

# Pull Request Key Information

## Reason for change

There was no documentation related to creating infrastructure files

## What was changed

Added more documentation

## Intended Purpose

Provide users with a detailed description of how to set the different infrastructure files

## Testing Completed

No code testing was done as only the user manual was updated.

The hyperlinks that have existing entries were tested to function correctly. However, it is important to note that there are hyperlinks that are currently placeholders for the entries that do not exist in the documentation yet.

2024-06-05 17:05 UTC, ThomasGalesloot requested changes
Great work! See my comments for some description nitpicks. Some general feedback: For each file I feel it would be helpful for users to describe what a row is supposed to represent. Also the formatting felt inconsistent when reading the documentation - can we tweak it a bit so that it feels like consistently structured

2024-06-05 17:05 UTC, ThomasGalesloot commented on USER_MANUAL.md
> +**Description:** A user define row name, that corresponds to the [repairable emission rate source](#emission_rate_source-repairable)(or [non-repairable](#emission_rate_source-non-repairable)) referen
Spelling/Grammar: defined not define

2024-06-05 17:05 UTC, ThomasGalesloot commented on USER_MANUAL.md
> +**Notes on acquisition:** User defined. In the future, the ``fit`` functionality will be reimplemented to enable fitting of sample data to the most appropriate statistical curve.
Lets leave out the part saying we will reimplement fit in the future

2024-06-05 17:05 UTC, ThomasGalesloot commented on USER_MANUAL.md
> +**Description:** Each row defines a single input. Depending on the [data use](#data-use) input, the values specify either individual emission rates (`sample`),  or the shape and scale of the distribu
Nit: Can you provide a little more detail about this

2024-06-05 17:10 UTC, SEAJang commented on USER_MANUAL.md
> +See [sites file](#sites-file) for details on how to set the parameter for simulation.
This is to link to the virtual world parameters.

2024-06-05 17:54 UTC, SEAJang commented on USER_MANUAL.md
> +- {method}_[deploy_year](#deployment_year)
Double-checked the code, and we only added it for site types, which doesn't make much sense. Fixed to also be able to set this for sites.

2024-06-05 20:28 UTC, SEAJang commented on USER_MANUAL.md
> +- [equipment](#equipment-sites-file)
That seems kind of redundant? This section is doing that.

2024-06-07 03:27 UTC, ThomasGalesloot requested changes
Overall great work! Really loving the structure now. I've commented some changes for the sites file only, but can you also make the equivalent changes for the other infrastructure files as well. After this, I'd like to do one more review just checking for little errors and grammar mistakes, but then this should be ready.

2024-06-07 03:27 UTC, ThomasGalesloot commented on USER_MANUAL.md
> +**Description:** This is a propagating parameter that can be set at multiple levels of granularity. See [emissions_production_rate](#emissions_production_rate-propagating-parameter) for more details
same comment as emissions production rate above

2024-06-07 03:27 UTC, ThomasGalesloot commented on USER_MANUAL.md
> +**Description:** This is a propagating parameter that can be set at multiple levels of granularity. See [duration](#duration-propagating-parameter) for more details on what this parameter represents.
same comment as for duration above

2024-06-07 03:27 UTC, ThomasGalesloot commented on USER_MANUAL.md
> +**Description:** This is a propagating parameter that can be set at multiple levels of granularity. See [multiple_emissions_per_source](#multiple_emissions_per_source-propagating-parameter) for more
same comment as for multiple emissions above

2024-06-07 03:27 UTC, ThomasGalesloot commented on USER_MANUAL.md
> +**Description:** This is a propagating parameter that can be set at multiple levels of granularity. See [deploy_year](#deployment_years--propagating-parameter) for more details on what this parameter
For the given site*

2024-06-07 03:27 UTC, ThomasGalesloot commented on USER_MANUAL.md
> +**Description:** This is a propagating parameter that can be set at multiple levels of granularity. See[deploy_month](#deployment_months--propagating-parameter) for more details on what this paramete
For the given site*

2024-06-07 03:27 UTC, ThomasGalesloot commented on USER_MANUAL.md
> +**Description:** This is a propagating parameter that can be set at multiple levels of granularity. See[spatial](#spatial-propagating-parameter) for more details on what this parameter represents. In
I don't feel great about this one but I don't have a suggestion on how to improve

2024-06-07 03:27 UTC, ThomasGalesloot commented on USER_MANUAL.md
> +**Description:** A True/False column that indicates whether the specified method will be deployed at the given site type. For example, if the value is set to `FALSE`, the emissions at the site will b
Nit: 2 amendments.
1.  A True/False column that indicates whether the specified method will be deployed at the given site.
2 but the method will not be deployed at that site*

2024-06-07 05:50 UTC, SEAJang commented on USER_MANUAL.md
> +      - [site\_ID](#site_id)
This will be a part of a different PR.

2024-06-08 22:11 UTC, ThomasGalesloot requested changes
Great work - Feel free to merge after handling this round of feedback

2024-06-08 22:11 UTC, ThomasGalesloot commented on USER_MANUAL.md
> +**Description:** A user-defined value that defines a specific equipment group for the simulation. These equipment groups influence how  `equipment level` [measurement scale](#measurement_scale)  meth
note each row must be a unique equipment

2024-06-08 22:11 UTC, ThomasGalesloot commented on USER_MANUAL.md
> +**Description:** The column header is a user defined value of a specific component in the simulation. The values in each column and row indicate how many counts of the given component(column) exists
Nit: The column header is a user defined value corresponding the identifier of a specific component defining as part of the simulation.

2024-06-08 22:11 UTC, ThomasGalesloot commented on USER_MANUAL.md
> +**Note:** The `source` column is often identical to the `emissions_rate_source` column. However it is in there incase users would like to use the same `emission_rate_sources`, for different `sources`
Can we make it clear that the values in the source column are distinct from the emissions rate source column and you do need to populate both to use an emissions rate source

2024-06-08 22:11 UTC, ThomasGalesloot commented on USER_MANUAL.md
> +**Description:** The number of days that the given non-persistent emission is active for at a given time.
Instead of active in the description can we emitting? I think it's more clear

2024-06-08 22:11 UTC, ThomasGalesloot commented on USER_MANUAL.md
> +
Instead of inactive, can we use non-emitting

2024-06-08 22:11 UTC, ThomasGalesloot commented on USER_MANUAL.md
> +**Description:** This is a propagating parameter that can be set at multiple levels of granularity. See [emissions_production_rate](#emissions_production_rate-propagating-parameter) for more details
This one didn't get updated to be in line with the new emissions rate source descriptions

2024-06-08 22:11 UTC, ThomasGalesloot commented on USER_MANUAL.md
> +**Description:** This is a propagating parameter that can be set at multiple levels of granularity. See[spatial](#spatial-propagating-parameter) for more details on what this parameter represents. In
Not detect the source, but an emissions coming from that source.

2024-06-08 22:11 UTC, ThomasGalesloot commented on USER_MANUAL.md
> +**Description:** A user defined row name, that corresponds to the [emissions rate source](#emissions_rate_source-propagating-parameter) references used in the virtual world parameters or in the infra
column?

2024-06-08 22:11 UTC, ThomasGalesloot commented on USER_MANUAL.md
> +**Description:** A user defined row name, that corresponds to the [emissions rate source](#emissions_rate_source-propagating-parameter) references used in the virtual world parameters or in the infra
Can we say something along the lines of it's essential just an ID

2024-06-08 22:11 UTC, ThomasGalesloot commented on USER_MANUAL.md
> +**Description:** The name of a distribution from the scipy library, only relevant if the row above is set to `dist`.
instead of saying row above can we say data use

2024-06-08 22:11 UTC, ThomasGalesloot commented on USER_MANUAL.md
> +**Description:** The maximum possible leak rate that can be sampled from a distribution, in grams per second.
emission rate not leak rate

2024-06-08 22:11 UTC, ThomasGalesloot commented on USER_MANUAL.md
> +- sample: Each row is a single emission value. LDAR-Sim randomly selects one of these values to generate a new emission.
For both sample and dist: each following row right?

2024-06-10 16:03 UTC, ThomasGalesloot approved these changes

2024-06-10 16:06 UTC, ThomasGalesloot commented on USER_MANUAL.md
> +**Description:** A True/False column that defines if the given emission source produces persistent(`TRUE`) or non-persistent(`FALSE`) emission. Non-persistent emissions have a total active duration o
Can we specify that non-persistent emissions start from their emitting state?

2024-06-10 16:06 UTC, ThomasGalesloot commented on USER_MANUAL.md
> +**Description:** A True/False column that defines if the given emission source produces persistent(`TRUE`) or non-persistent(`FALSE`) emission. Non-persistent emissions have a total active duration o
and then cycle between emitting and not emitting

2024-06-10 16:12 UTC, merged