Emissions creation typerror fix
LDAR-Sim/LDAR_Sim pull request #289
Opened 2024-08-13 20:51 UTC by ThomasGalesloot

# Pull Request Key Information

## Reason for change

Fix type-error that occur with emissions creation

## What was changed

Add typecasting to avoid type-errors.

## Intended Purpose

Prevent type-errors during runtime

## Level of version change required

Patch

## Testing Completed

Manual testing using modified sites file to produce error (Added emissions duration): 
[facilities_Perm_for_test.csv](https://github.com/user-attachments/files/16605098/facilities_Perm_for_test.csv)

All other input are parameter were sourced from simple_test_case1

All unit tests passing:
[unit_test_results.txt](https://github.com/user-attachments/files/16605164/unit_test_results.txt)

All E2E test passing: C:\Users\ThomasGalesloot\Documents\GitHub\LDAR_Sim_Dev\LDAR_Sim\testing\end_to_end_testing\test_results\V4_simple_non_repairable_emissions_5f77e95675f2c4286e250f910aac2e7374cafc0c.log
C:\Users\ThomasGalesloot\Documents\GitHub\LDAR_Sim_Dev\LDAR_Sim\testing\end_to_end_testing\test_results\V4-simple_repairable_emissions_5f77e95675f2c4286e250f910aac2e7374cafc0c.log
## Target Issue

N/A

## Additional Information

N/A

2024-08-13 21:03 UTC, SEAJang requested changes
Please double check the sources.py for more self._emis_duration if you are going to hard cast it to a float.

2024-08-14 00:00 UTC, ThomasGalesloot commented
Latest E2E test results: 
[V4-simple_repairable_emissions_cac2f907ebce2287ff6df7ce8ed6716c85216475.log](https://github.com/user-attachments/files/16606330/V4-simple_repairable_emissions_cac2f907ebce2287ff6df7ce8ed6716c85216475.log)
[V4_simple_non_repairable_emissions_cac2f907ebce2287ff6df7ce8ed6716c85216475.log](https://github.com/user-attachments/files/16606331/V4_simple_non_repairable_emissions_cac2f907ebce2287ff6df7ce8ed6716c85216475.log)

Latest Unit test results: 
[unit_test_results.txt](https://github.com/user-attachments/files/16606338/unit_test_results.txt)

2024-08-14 00:00 UTC, ThomasGalesloot commented
> Please double check the sources.py for more self._emis_duration if you are going to hard cast it to a float.

Remove all typecasts except for the initial value setting

2024-08-14 01:15 UTC, SEAJang approved these changes

2024-08-14 16:03 UTC, merged