Added Unit testing with pytest
LDAR-Sim/LDAR_Sim pull request #48
Opened 2023-06-01 15:20 UTC by ThomasGalesloot

Added initial file structure and sample unit tests. Updated requirements to support unit testing.
Tested with end-to-end testing to ensure no functional changes to LDAR-Sim. Logs will be attached. [unit_testing_logs.zip](https://github.com/LDAR-Sim/LDAR_Sim/files/11626945/unit_testing_logs.zip)

2023-06-01 19:48 UTC, SEAJang requested changes
Could we get some sort of naming / numbering convention for the unit tests, add that into the documentation and change the existing unit tests to follow the convention that is written out? 
Otherwise, it's looks good.

2023-06-02 15:34 UTC, KeeganShaw-GIS requested changes
This looks awesome. Agree with Sally's comments. And just double check the spelling of crew testing

2023-06-02 15:34 UTC, KeeganShaw-GIS commented on LDAR_Sim/testing/unit_testing/test_methods/crew_testing_fixutres.py
> +
File name has a spelling mistake I think?

2023-06-02 23:51 UTC, ThomasGalesloot commented
> Could we get some sort of naming / numbering convention for the unit tests, add that into the documentation and change the existing unit tests to follow the convention that is written out? Otherwise, it's looks good.

Unit testing has been refactored to have a consistent file structure and naming convention

2023-06-06 17:43 UTC, KeeganShaw-GIS approved these changes

2023-06-06 17:45 UTC, merged