Static site venting
LDAR-Sim/LDAR_Sim pull request #50
Opened 2023-06-05 18:45 UTC by ThomasGalesloot

Added Static site level that can be specified in the infrastructure file. Removed options to use vent file (containing site level emissions rates) at a program level to obtain venting rates. Added new output to track method visits to visits.

2023-06-06 04:18 UTC, SEAJang commented on USER_MANUAL.md
Should the older/deprecated parameters be left in and labeled deprecated instead of being completely removed from the user manual? Potentially point towards which parameter(s) it may have been replaced with?

2023-06-06 04:18 UTC, SEAJang commented on changelog.md
Should the version/tagging be added into the change log?

2023-06-06 17:09 UTC, ThomasGalesloot commented on USER_MANUAL.md
My thought/understanding was that this was supposed to be a live document and stay up to date with the current functionality. I was thinking it might be confusing to keep something in there that has been removed. Perhaps if we had a older parameters/inputs section that briefly listed them and the version in which they were removed it could live there? Is that something I should add?

2023-06-06 17:11 UTC, ThomasGalesloot commented on changelog.md
I've been tagging the merge commit on master - So while I do think this makes sense to reference the version - There is going to be a little bit of weirdness with how we currently do things around there will be a reference in the PR to a version that doesn't exist until it gets merged? If I tag the tip of the branch - how does that work once the PR gets merged/if I need to update code as part of the review process?

2023-06-06 20:41 UTC, KeeganShaw-GIS requested changes
Change that one thing

2023-06-13 17:52 UTC, SEAJang approved these changes
Looks good.

2023-06-13 21:43 UTC, KeeganShaw-GIS approved these changes
Looks great

2023-06-13 21:43 UTC, KeeganShaw-GIS commented on LDAR_Sim/src/methods/crew.py
> +    def gen_site_vis_rec(self, site_detect_results, site) -> dict[str, Any]:
Nice!

2023-06-13 22:56 UTC, merged