Add Venting and Leak File inputs for subtypes
LDAR-Sim/LDAR_Sim pull request #52
Opened 2023-06-15 02:49 UTC by ThomasGalesloot

Added the option in the subtype file to provide venting and leak file inputs to sample from to inform vent and leak rates respectively.

Reason for change: Previously, sampling from leak rates was only possible at a program level. To increase simulation accuracy, it has been requested that the ability to sample at a subtype level should be added. For venting, sampling at a subtype level is also desired as an alternative to provided site level static venting rates.

All E2E tests are passing: 
[testing_logs.zip](https://github.com/LDAR-Sim/LDAR_Sim/files/11752182/testing_logs.zip)

2023-06-15 02:52 UTC, ThomasGalesloot commented
3 questions:
1. Should this be split into 2 PR's, one for leak files in the subtype file and 1 for vent files in the subtype file?
2. Should I upload another subtype_distributions file in the inputs folder to serve as an example?
3. As unit testing these code changes is difficult, should I add new end to end test(s) to test this functionality?

2023-06-15 04:23 UTC, SEAJang commented
1. One PR is fine I think just because they build on the same feature
2. Another example that showcases the feature added is always useful. So yes.
3. Yes.

2023-06-15 06:40 UTC, SEAJang requested changes
Other than the minor changes related to documentation and the E2E testing mentioned in the PR comments, it looks good.

2023-06-15 06:40 UTC, SEAJang commented on LDAR_Sim/src/utils/emis_inputs.py
> +    for st_idx, subtype in program['subtypes'].items():
Should there be doc string?

2023-06-15 15:12 UTC, ThomasGalesloot commented on USER_MANUAL.md
> +**Description:** Imports a lookup table that allows the modeler to set the leak rate source, vent_rate_file, NRd and LPR per facility according to subtype type. This functionality can be used when th
Modeler is actually used in the user manual - That is where I got it from

2023-06-15 15:23 UTC, ThomasGalesloot commented on USER_MANUAL.md
> +**Description:** Imports a lookup table that allows the modeler to set the leak rate source, vent_rate_file, NRd and LPR per facility according to subtype type. This functionality can be used when th
Are we using the term "user" in other places?

2023-06-15 19:10 UTC, ThomasGalesloot commented on LDAR_Sim/src/utils/emis_inputs.py
> +    for st_idx, subtype in program['subtypes'].items():
Done

2023-06-15 19:11 UTC, ThomasGalesloot commented on USER_MANUAL.md
> +**Description:** Imports a lookup table that allows the modeler to set the leak rate source, vent_rate_file, NRd and LPR per facility according to subtype type. This functionality can be used when th
Resolution: Both user and modeler are used. A separate change will be authored to make wording consistent.

2023-06-15 19:14 UTC, ThomasGalesloot commented on changelog.md
> +
Done

2023-06-15 23:09 UTC, ThomasGalesloot commented
Sally's concerns/comments have now been addressed. Ready for review.

2023-06-16 16:08 UTC, SEAJang approved these changes
Looks good

2023-06-16 19:30 UTC, KeeganShaw-GIS approved these changes
Awesome work.

2023-06-16 19:53 UTC, merged