feat: Add Git commit template
LDAR-Sim/LDAR_Sim pull request #68
Opened 2023-06-27 19:04 UTC by ThomasGalesloot

Reason for change: With new focus on proper coding conventions and standards, a standard commit message template is required.

What was changed: 
Added a git commit template along with instructions on how to set it up to LDAR-Sim. 

Intended Purpose: This pull request aims to provide users with a commit message template for LDAR-Sim so that they do not need to manually copy/follow a standard commit message template from documentation for each commit.

Level of version change required: No change

2023-06-28 03:40 UTC, SEAJang requested changes

2023-06-28 03:40 UTC, SEAJang commented on LDAR_Sim/install/SetupIntructions.md
The Git commit template is great!
One change I think is needed is a warning or note as an FYI in the document regarding the use of the commit template. 
In some cases, the commented lines that describe the valid types, and what users are to put in each section do not show in the IDE. And if the IDE is opened in a very small window, the template could look like it only has 1 line.  
This could be done by just having the commit template shown in md so users know what to expect.

2023-06-28 15:13 UTC, ThomasGalesloot commented on LDAR_Sim/install/SetupIntructions.md
The tricky thing with the commit template is that VSCODE filters out any commented lines (the descriptions) to show you what the actual commit message will look like which I agree is not so useful. The thing is that we do want to actual commit to look like this and it does show up properly when committing through git. I wonder if this is more an IDE setting issue than anything else?

2023-06-28 19:41 UTC, ThomasGalesloot commented
Rebased to resolve typo in commit message without requiring separate commit for fix

2023-06-28 20:53 UTC, ThomasGalesloot commented on LDAR_Sim/install/SetupIntructions.md
For Users using VS Code set the setting git.showCommitInput to false to resolve this.

2023-06-29 05:27 UTC, SEAJang approved these changes
Looks Great!

2023-07-11 19:43 UTC, merged